name: .NET Build and Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    name: Build .NET App and Publish Single File

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true /p:DebugType=None /p:DebugSymbols=false -o ./publish

    - name: List published files
      run: dir .\publish\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-csharp-app-executable
        path: ./publish/